{"name": "Test of failed attempt to get user orders without authorization", "status": "passed", "description": "Negative test of the endpoint \"Получение заказов конкретного пользователя\" GET /api/orders.Checks that response code is 401 that response body contains all required fieldsand that request returns \"success\": false", "start": 1701420707490, "stop": 1701420708881, "uuid": "8da6a5c2-0e85-4537-90eb-b940c66b3458", "historyId": "93377173a641d4dfe08f02262c107afc", "testCaseId": "93377173a641d4dfe08f02262c107afc", "fullName": "tests.test_get_user_orders.TestGetUserOrders#test_get_user_orders_without_authorization_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "Airforce3"}, {"name": "thread", "value": "10084-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}