{"name": "Test of failed attempt to create an order without authorization", "status": "failed", "statusDetails": {"message": "AssertionError: Instead of code 401 received code 200\nassert 200 == 401\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_order_creation.TestOrderCreation object at 0x00000240E735ABD0>\n\n    @allure.title('Test of failed attempt to create an order without authorization')\n    @allure.description('Test of the endpoint \"Создание заказа\" POST /api/orders.'\n                        'Checks that order creation is impossible without authorization '\n                        'that response body contains all main required fields,'\n                        'and that request returns \"success\": False')\n    def test_order_creation_without_authorization_failed(self):\n        payload = {\"ingredients\": [\"61c0c5a71d1f82001bdaaa6d\"]}\n        response = requests.post(Urls.create_order_url, data=payload)\n        \"\"\"Согласно документации, логике работы сайта и здравому смыслу,\n        неавторизованный пользователь не может оформить заказ\n        (раздел \"Авторизация и регистрация\", стр 5 - \"Только авторизованные пользователи могут делать заказы\").\n        Так как в документации нет примера ответа для такого случая, то в качестве образца принят\n        ответ на запрос изменения данных пользователя:\n        \"Если выполнить запрос без авторизации, вернётся код ответа 401 Unauthorized.\n        {\"success\": false, \"message\": \"You should be authorised\"}\"\"\"\n>       assert response.status_code == 401, f'Instead of code 401 received code {response.status_code}'\nE       AssertionError: Instead of code 401 received code 200\nE       assert 200 == 401\nE        +  where 200 = <Response [200]>.status_code\n\ntests\\test_order_creation.py:40: AssertionError"}, "description": "Test of the endpoint \"Создание заказа\" POST /api/orders.Checks that order creation is impossible without authorization that response body contains all main required fields,and that request returns \"success\": False", "start": 1701704340630, "stop": 1701704341133, "uuid": "a22f3ea6-bbd2-451b-8612-432b97129106", "historyId": "bdd7ec42b810dddcd700106118a0da1d", "testCaseId": "bdd7ec42b810dddcd700106118a0da1d", "fullName": "tests.test_order_creation.TestOrderCreation#test_order_creation_without_authorization_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_creation"}, {"name": "subSuite", "value": "TestOrderCreation"}, {"name": "host", "value": "Airforce3"}, {"name": "thread", "value": "9092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_creation"}]}